name: Application Deploying On AWS

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

env:
  VERSION: v1
  AWS_ACCOUNT_ID: 118107592194
  REGION: us-east-1
  ECR_REPOSITORY: flaskapp-simple-bank
  IMAGE: 118107592194.dkr.ecr.us-east-1.amazonaws.com/flaskapp-simple-bank
  S3_BUCKET: s3://118107592194-devops-scripts

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: sourabh-devops07/banking-app-2-tier
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::118107592194:role/github-action-deploy-role
          aws-region: ${{ env.REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | \
          docker login \
            --username AWS \
            --password-stdin \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com

          echo "✅ Login Successful to Amazon ECR"

      - name: Upload Docker Compose to S3
        run: |
          aws s3 cp docker-compose.yml \
            ${{ env.S3_BUCKET }}/docker-compose.yml \
            --region ${{ env.REGION }}

          echo "✅ Docker Compose Uploaded Successfully"

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ env.IMAGE }}:${{ env.VERSION }} \
            -t ${{ env.IMAGE }}:latest \
            .

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ env.IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE }}:latest

          echo "✅ Docker Image Pushed Successfully"