name : Application Deploying On AWS

on:
  workflow_call:

  
permissions:
  id-token: write
  contents: read  

env:
  VERSION: v1
  IMAGE: 118107592194.dkr.ecr.us-east-1.amazonaws.com/flaskapp-simple-bank
  REGION: us-east-1
  S3_BUCKET: s3://118107592194-devops-scripts

jobs:
  build-and-deploy:
    runs-on: ubunut-latest
    steps:
      - uses: action/checkout@v4
        with:
          repository: sourabh-devops07/banking-app-2-tier
          ref: main

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::118107592194:role/github-action-deploy-role
          aws-region: ${{ env.REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | \
          docker login --username AWS --password-stdin \
          118107592194.dkr.ecr.${{ env.REGION }}.amazonaws.com
          echo "Login Successfull to ECR ✅"


      - name: UploadDocker-Compose to s3
        run: |
          aws s3 mb ${{ env.S3_BUCKET }} --region ${{ env.REGION }} 2>/dev/null || true
          aws s3 cp docker-compose.yml ${{ env.S3_BUCKET }}/docker-compose.yml --region ${{ env.REGION }}
          echo "Docker Compose file uploaded to S3 ✅"

      - name: Deploy via SSM
        run: |
          CMD_ID=$(aws ssm send-command \
          --target "Key=tag:App,Values=flask" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy ${{env.VERSION}} by {{github.actor}}" \
          --parameters '{"commands":[
          "set -e"
          "aws ecr get-login-password --region ${{ env.REGION }} | \
          docker login --username AWS --password-stdin \
          118107592194.dkr.ecr.${{ env.REGION }}.amazonaws.com",
          
          "mkdir -p /home/ubuntu/app",
          "aws s3 cp ${{ env.S3_Bucket }}"]}')      