name: Main Pipeline for Orchestrate

on:
  push:
    branches:
      - main
    workflow_dispatch:
jobs:
 verify_connection:
   uses: ./.github/workflows/test_connection.yml
   permissions:
     id-token: write
     contents: read   

test_fleet_health_envs:
  needs: verify_connection
  uses: ./.github/workflows/test_fleet_health.yml
  Permissions:
    id-token: write
    contents: read

Smoke_test:
  needs: test_fleet_health_envs
  uses: ./.github/workflows/smoke_test.yml
  Permissions:
    id-token: write
    contents: read  


build_push:
  needs: Smoke_testing
  uses: ./.github/workflows/build_push.yml
  Permissions:
    id-token: write
    contents: read

deploying:
  needs: Smoke_testing
  uses: ./.github/workflows/deploy.yml
  Permissions:
    id-token: write
    contents: read    
