name: Test Connection For Pipeline

on:
  workflow_dispatch

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "GitHub Action is working successfully ✅"