name: Test Fleet health and Env Variables

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::720800607391:role/github-action-deploy-role  # yha khud ka dalna arn number ye ni h mera ok chnge krna
          aws-region: us-east-1

      - name: Print Priva
        run: |
          CMD_ID=$(aws ssm send-command \
            --targets "Key=tag:App,Values=flask" \
            --document-name "AWS-RunShellScript" \
            --parameters '{"commands":["hostname -I", "docker --version" 2>/de/null || echo "Docker not installed",
             "aws --version 2>/de/null || echo "AWS CLI not installed"", "mysql --version 2>/de/null || echo "MySQL not installed""
             "aws ssm get-parameter-by-path --path /appliccation/banking --with-decryption --region us-east-1"]}' \
            --query 'Command.CommandId' \
            --output text --region us-east-1)
            
            echo "cmd_id: $CMD_ID" >> $GITHUB_OUTPUT

            name: Show Results
            id: health
          
            sleep 30

          aws ssm list-command-invocations \
            --command-id "&{{steps.health.outputs.cmd_id}}" --details \
            --region us-east-1
            --query "CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}" \
            --output table
            )