name: Test Workflow
on:
  push:
    branches:
      - main
job:
  working-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "Github Action is working successfully ✅"